# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Question1(object):
    def setupUi(self, Question1):
        Question1.setObjectName("Question1")
        Question1.resize(720, 400)
        self.label_0 = QtWidgets.QLabel(Question1)
        self.label_0.setGeometry(QtCore.QRect(50, 60, 600, 40))
        self.label_0.setStyleSheet("color: rgb(255, 52, 59);\n"
"font: 18pt \"Menlo\";")
        self.label_0.setScaledContents(True)
        self.label_0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_0.setWordWrap(True)
        self.label_0.setObjectName("label_0")
        self.label_1 = QtWidgets.QLabel(Question1)
        self.label_1.setGeometry(QtCore.QRect(50, 200, 600, 40))
        self.label_1.setStyleSheet("color: rgb(255, 73, 62);\n"
"font: 18pt \"Menlo\";")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setWordWrap(True)
        self.label_1.setObjectName("label_1")

        self.retranslateUi(Question1)
        QtCore.QMetaObject.connectSlotsByName(Question1)

    def retranslateUi(self, Question1):
        _translate = QtCore.QCoreApplication.translate
        Question1.setWindowTitle(_translate("Question1", "Form"))
        self.label_0.setText(_translate("Question1", "TextLabel"))
        self.label_1.setText(_translate("Question1", "TextLabel"))
