# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Question2(object):
    def setupUi(self, Question2):
        Question2.setObjectName("Question2")
        Question2.resize(720, 400)
        self.label_result = QtWidgets.QLabel(Question2)
        self.label_result.setGeometry(QtCore.QRect(60, 80, 600, 240))
        self.label_result.setStyleSheet("color: rgb(91, 97, 255);\n"
"font: 14pt \"Menlo\";")
        self.label_result.setScaledContents(True)
        self.label_result.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_result.setWordWrap(True)
        self.label_result.setObjectName("label_result")

        self.retranslateUi(Question2)
        QtCore.QMetaObject.connectSlotsByName(Question2)

    def retranslateUi(self, Question2):
        _translate = QtCore.QCoreApplication.translate
        Question2.setWindowTitle(_translate("Question2", "Form"))
        self.label_result.setText(_translate("Question2", "TextLabel"))
