# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question_0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Question0(object):
    def setupUi(self, Question0):
        Question0.setObjectName("Question0")
        Question0.resize(720, 400)
        self.title = QtWidgets.QLabel(Question0)
        self.title.setGeometry(QtCore.QRect(60, 0, 600, 30))
        self.title.setStyleSheet("color: rgb(135, 68, 255);\n"
"font: 700 18pt \"Menlo\";")
        self.title.setScaledContents(True)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.video_widget = QVideoWidget(Question0)
        self.video_widget.setGeometry(QtCore.QRect(40, 30, 640, 360))
        self.video_widget.setObjectName("video_widget")

        self.retranslateUi(Question0)
        QtCore.QMetaObject.connectSlotsByName(Question0)

    def retranslateUi(self, Question0):
        _translate = QtCore.QCoreApplication.translate
        Question0.setWindowTitle(_translate("Question0", "Form"))
        self.title.setText(_translate("Question0", "TextLabel"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
