# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'label_0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LabelContainer(object):
    def setupUi(self, LabelContainer):
        LabelContainer.setObjectName("LabelContainer")
        LabelContainer.resize(400, 300)
        self.label = QtWidgets.QLabel(LabelContainer)
        self.label.setGeometry(QtCore.QRect(50, 20, 58, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")

        self.retranslateUi(LabelContainer)
        QtCore.QMetaObject.connectSlotsByName(LabelContainer)

    def retranslateUi(self, LabelContainer):
        _translate = QtCore.QCoreApplication.translate
        LabelContainer.setWindowTitle(_translate("LabelContainer", "Form"))
        self.label.setText(_translate("LabelContainer", "TextLabel"))
