# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Container(object):
    def setupUi(self, Container):
        Container.setObjectName("Container")
        Container.resize(800, 400)
        self.video_container = QtWidgets.QWidget(Container)
        self.video_container.setGeometry(QtCore.QRect(0, 20, 800, 360))
        self.video_container.setObjectName("video_container")
        self.widget = QVideoWidget(self.video_container)
        self.widget.setGeometry(QtCore.QRect(80, 0, 640, 360))
        self.widget.setObjectName("widget")

        self.retranslateUi(Container)
        QtCore.QMetaObject.connectSlotsByName(Container)

    def retranslateUi(self, Container):
        _translate = QtCore.QCoreApplication.translate
        Container.setWindowTitle(_translate("Container", "Form"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
