# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'container.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_container(object):
    def setupUi(self, container):
        container.setObjectName("container")
        container.resize(829, 723)
        container.setStyleSheet("background-image: url(:/images/kkx.jpeg);")
        self.label = QtWidgets.QLabel(container)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 400))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/kkx.jpeg"))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(container)
        self.widget.setGeometry(QtCore.QRect(180, 470, 321, 151))
        self.widget.setObjectName("widget")

        self.retranslateUi(container)
        QtCore.QMetaObject.connectSlotsByName(container)

    def retranslateUi(self, container):
        _translate = QtCore.QCoreApplication.translate
        container.setWindowTitle(_translate("container", "container"))
import resources_rc
